error = {
    1: "Error! Unknown keyword",
    2: "Error! unknown syntax"
}

def error_call(x):
    return error[x]
    quit()
